---
title: "Dunwich Forest"
author: "Julian Flowers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, fig.width= 10, fig.height = 7 )


```

```{r load}
#pak::pak("julianflowers/sentinelBurnR")
library(sentinelBurnR)
library(terra)
library(sf)
library(dplyr)
library(ggplot2)
library(mapview)
library(stars)
library(cowplot)
```

```{r aoi}
dunwich_centroid <- st_sfc(
    st_point(c(646315, 271425)),
    crs = 27700
)

buffer <- st_buffer(dunwich_centroid, 4000)

# Your existing Dunwich Forest AOI
aoi <- st_as_sf(buffer)

aoi <- read_aoi(aoi)
#mapview(st_as_sf(aoi$geometry))
```


```{r searches}

spring <- search_s2(
    aoi,
    start = "2026-04-01",
    end   = "2026-07-01"
)

summer <- search_s2(
    aoi,
    start = "2026-07-01",
    end   = "2026-09-01"
)


```

```{r select dates}
spring_sel <- select_timeseries(
    spring,
    interval = 10,
    max_cloud = 30
)

summer_sel <- select_timeseries(
    summer,
    interval = 10,
    max_cloud = 30
)


```

```{r download}

spring_collection <- download_s2(
    spring_sel,
    assets = c(
        "red",
        "nir08",
        "swir16",
        "swir22",
        "scl"
    )
)

summer_collection <- download_s2(
    summer_sel,
    assets = c(
        "red",
        "nir08",
        "swir16",
        "swir22",
        "scl"
    )
)

```

```{r analyse vegetation}

spring_veg <- analyse_vegetation(spring_collection, cache = TRUE, overwrite = TRUE)

summer_veg <- analyse_vegetation(summer_collection)


```

```{r}

plot(st_as_stars(spring_veg$ndmi), col = palette_lookup(name = "moisture"))

plot(st_as_stars(summer_veg$ndmi), col = palette_lookup(name = "moisture"))

plot(spring_veg$ndvi, col = palette_lookup(name = "vegetation"))

plot(summer_veg$ndvi, col = palette_lookup(name = "vegetation"))

plot(spring_veg$msi, col = palette_lookup(name = "stress"))

plot(summer_veg$msi, col = palette_lookup(name = "stress"))



```



```{r arranged plots}

library(ggplot2)
library(stars)
library(patchwork)

p_ndvi <- ggplot() +
    geom_stars(
        data = st_as_stars(spring_veg$ndvi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "vegetation",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "NDVI",
        fill = "NDVI"
    ) +
    theme_minimal()

p_ndmi <- ggplot() +
    geom_stars(
        data = st_as_stars(spring_veg$ndmi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "moisture",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "NDMI",
        fill = "NDMI"
    ) +
    theme_minimal()

p_msi <- ggplot() +
    geom_stars(
        data = st_as_stars(spring_veg$msi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "stress",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "MSI",
        fill = "MSI"
    ) +
    theme_minimal()


p_msi_s <- ggplot() +
    geom_stars(
        data = st_as_stars(summer_veg$msi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "stress",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "MSI-Summer",
        fill = "MSI"
    ) +
    theme_minimal()

p_ndvi_s <- ggplot() +
    geom_stars(
        data = st_as_stars(summer_veg$ndvi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "vegetation",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "NDVI-Summer",
        fill = "NDVI"
    ) +
    theme_minimal()

p_ndmi_s <- ggplot() +
    geom_stars(
        data = st_as_stars(summer_veg$ndmi)
    ) +
    scale_fill_gradientn(
        colours = palette_lookup(
            "moisture",
            256
        )
    ) +
    coord_equal() +
    labs(
        title = "NDMI-Summer",
        fill = "NDMI"
    ) +
    theme_minimal()



(p_ndvi | p_ndmi | p_msi) / (p_ndvi_s | p_ndmi_s | p_msi_s) +
    plot_annotation(
        title = "Vegetation and moisture condition"
    ) &
    theme(
        axis.title = element_blank()
    )

```



```{r, eval=FALSE}

ndmi <- sentinel_timeseries(
    collection,
    index = "ndmi",
    boundary = aoi
)

msi <- sentinel_timeseries(
    collection,
    index = "msi",
    boundary = aoi
)
```

```{r, eval=FALSE}
plot_timeseries(
    ndmi,
    index = "NDMI"
)

plot_timeseries(
    msi,
    index = "MSI"
)
```

```{r}


visual_collection_spring <- download_s2(
    spring_sel,
    assets = c(
        "visual"
    )
)

visual_collection_summer <- download_s2(
    summer_sel,
    assets = c(
        "visual"
    )
)
```

```{r}

visual_jul29 <- read_visual(
    visual_collection_summer,
    date = "2026-07-29",
    aoi = aoi
)

rgb <- st_as_stars(visual_jul29)

plot(rgb, rgb = 1:3)


```

```{r, eval=FALSE}
visual_jun24 <- read_visual(
    visual_collection_summer,
    date = "2026-06-24",
    aoi = aoi
)


```

```{r}

visual_aug13 <- read_visual(
    visual_collection_summer,
    date = "2026-08-13",
    aoi = aoi
)

visual_aug25 <- read_visual(
    visual_collection_summer,
    date = "2026-08-25",
    aoi = aoi
)

#terra::plotRGB(visual_jun24)
terra::plotRGB(visual_jul29)
terra::plotRGB(visual_aug13)
terra::plotRGB(visual_aug25)

```

```{r, eval=FALSE}

mapview(spring_veg$msi, maxpixels = 639200, col.regions = palette_lookup("stress")) +
    mapview(spring_veg$ndvi, maxpixel = 639200, col.regions = viridis::viridis(256))

```


```{r get humidity}



cat(
    "\n=== CDS DIAGNOSTIC ===\n",
    "CDS_API_KEY available: ",
    nzchar(Sys.getenv("CDS_API_KEY")),
    "\n======================\n"
)

cds_key <- Sys.getenv(
    "CDS_API_KEY",
    unset = ""
)

if (nzchar(cds_key)) {
    ecmwfr::wf_set_key(
        key = cds_key,
        user = "ecmwfr"
    )
}

climate <- get_humidity(
    boundary = read_boundary(aoi$geometry),
    start = "2026-04-01",
    end   = "2026-08-31"
)

rainfall <- get_rainfall(boundary = read_boundary(aoi$geometry),
    start = "2026-04-01",
    end   = "2026-08-31"
    )


rainfall

```

```{r, eval=FALSE}

rain_7d <- do.call(
    rbind,
    purrr::map(
        summer_veg$date,
        antecedent_rainfall,
        rainfall = rainfall,
        days = 7
    )
) |>
    dplyr::rename(
        rainfall_7d = rainfall_mm,
        rainfall_days_7d = n_days
    )

                                                                                                                                                                                                                                                                                                                                        frrrrain_30d <- do.call(
    rbind,
    lapply(
        summer_veg$date,
        antecedent_rainfall,
        rainfall = rainfall,
        days = 30
    )
) 
    dplyr::rename(
        rainfall_30d = rainfall_mm,
        rainfall_days_30d = n_days
    )

condition <- condition |>
    dplyr::left_join(
        rain_7d,
        by = "date"
    ) |>
    dplyr::left_join(
        rain_30d,
        by = "date"
    )

condition

```


